language: node_js
node_js:
  - 8
sudo: false
env:
  - NODE_ENV='test'
script:
  - yarn

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      before_install:
        - nvm install 7
        - node --version
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      script:
        - cd bin