language: node_js
sudo: false

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      before_install:
        - nvm install 8
        - npm install npm@latest -g.
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - npm install -g detox-cli
        - npm install -g exp@53.0.0
        - npm i
      script:      
        - mkdir -p bin/Exponent.app
        - wget -qO- https://dpq5q02fu5f55.cloudfront.net/Exponent-2.5.1.tar.gz | tar xvz -C $TRAVIS_BUILD_DIR/bin/Exponent.app
        - exp start --offline &
        - npm run e2e