language: node_js
node_js:
  - 8
sudo: false
env:
  - NODE_ENV='test'

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      before_install:
        - nvm install 8
        - node --version
      install:
        - brew tap wix/brew
        - brew install applesimutils
        - brew install git-lfs
        - npm install -g detox-cli
        - npm install -g react-native-cli
        - npm install -g exp
        - npm i
      script:      
        - git lfs install
        - git lfs pull
        - pwd
        - mkdir -p bin1/Exponent1.app
        - wget -qO- https://dpq5q02fu5f55.cloudfront.net/Exponent-2.4.6.tar.gz | tar xvz -C $TRAVIS_BUILD_DIR/bin/Exponent1.app
        - npm run e2e